version: "2"
services:
  webserver:
    env_file:
      - config.env
    build: 
      context: .
      args:
        COURSE_BACKUP_FILE_ARG: ${COURSE_BACKUP_FILE}
    depends_on:
      - db
    volumes:
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    command: 
      ["sh", "/tmp/setup/install_moodle.sh"]
  db:
    image: mariadb:10.7
    volumes:
      - moodle-database:/config/databases/
      - moodle-database:/var/lib/mysql
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
volumes:
  moodle-database: