version: "2"
services:
  webserver:
    env_file:
      - config.env
    build: 
      context: .
      args:
        COURSE_BACKUP_FILE_ZQ_ARG: ${COURSE_BACKUP_FILE_ZQ}
        COURSE_BACKUP_FILE_DQR5_ARG: ${COURSE_BACKUP_FILE_DQR5}
        DEBUG: ${DEBUG}
    depends_on:
      - db
    volumes:
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    command: 
      ["sh", "/tmp/setup/install_moodle.sh"]
    ports:
      - "${MOODLE_SERVER_PORT}:80"

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}