version: "2"
services:
  # webserver:
  #   depends_on:
  #     - chatbot
  chatbot:
    build: ./chatbot/
    env_file:
      - config.env
    depends_on:
      - db
      - webserver
    command: >
      bash -c "cd /chatbot/
      && python run_server.py"
      # ["tail", "-f", "/dev/null"]
    ports:
      - "44123:44123"
