services:
  hub-db:
    image: postgres:alpine3.18
    container_name: jupyterhub-db
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      POSTGRES_DB: jupyterhub
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "db:/var/lib/postgresql/data"
    ports:
      - "${JUPYTER_DB_PORT}:5432"

  lab:
    image: jupyterlab
    env_file:
      - config.env
    environment:
      MOODLE_SERVER_URL: ${MOODLE_SERVER_URL}
    build:
      context: ./jupyter-notebooks/jupyterlab

  hub:
    depends_on:
      - hub-db
      - lab
    links:
      - hub-db
    env_file:
      - config.env
    image: jupyterhub
    build:
      context: ./jupyter-notebooks/jupyterhub
    container_name: jupyterhub # container name needs to match c.JupyterHub.hub_ip in jupyterhub_config.py
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "data:/data"
    environment:
      MOODLE_SERVER_URL: ${MOODLE_SERVER_URL}
      DOCKER_JUPYTER_HUB_CONTAINER_NAME: jupyterhub
      DOCKER_JUPYTER_IMAGE: jupyterlab
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      POSTGRES_HOST: hub-db
      POSTGRES_DB: jupyterhub
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JUPYTER_API_TOKEN: ${JUPYTER_API_TOKEN}
    ports:
      - "${JUPYTER_HUB_PORT}:8000"

  gradeservice:
    image: gradeservice
    env_file:
      - config.env
    build:
      context: ./jupyter-notebooks/gradeservice
    container_name: gradeservice
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET}
      GRADING_TIMEOUT: ${GRADING_TIMEOUT}
      ASSIGNMENTS_PATH: ${ASSIGNMENTS_PATH}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "gradeservice_data:/assignments"
    ports:
      - "${JUPYTER_GRADESERVICE_PORT}:5000"

volumes:
  data:
    name: jupyterhub_data
    driver: local
  db:
    name: jupyterhub_db
    driver: local
  gradeservice_data:
    name: gradeservice_data
    driver: local

