version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_APP: "true"
  moodleapp:
    image: node:${MOODLE_DOCKER_APP_NODE_VERSION:-14}
    working_dir: /app
    command: npm start -- --host 0.0.0.0
    volumes:
      - "${MOODLE_DOCKER_APP_PATH}:/app"
    expose:
      - 8100
      - 35729
      - 53703
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
