version: "2"
services:
  webserver:
    environment:
      MOODLE_DOCKER_APP: "true"
      MOODLE_DOCKER_APP_PORT: 80
  moodleapp:
    image: "moodlehq/moodleapp:${MOODLE_DOCKER_APP_VERSION}"
    ports:
      - "8100:80"
